### ISSUE TITLE
[BUG] Superwall triggers main thread warning

### ISSUE THREAD

**Issue by lewis-smith** [superwall-me/paywall-ios#69] opened 2022-09-29 11:25 UTC
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `Paywall` version: 2.5.0
- iOS version(s): 16.1 b3
- CocoaPods/Carthage version (if applicable): 1.11.3
- Xcode version: 14.1.0 b3
- Devices/Simulators affected: iPhone
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Describe the bug
Runtime error: `This method should not be called on the main thread as it may lead to UI unresponsiveness.`
I see the error around 10 times

The stack trace does not point to supernal, but if remove superwall it doesn't happen and if I re-add it it does.

### Steps to reproduce
1. Add Superwall pod
2. Add code to configure supernal
3. Run project

### Other Information
```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00000001e2281d08 in os_log_fault_default_callback ()
#1	0x00000001e227830c in _os_log_impl_flatten_and_send ()
#2	0x00000001e22751bc in _os_log ()
#3	0x00000001e227d168 in _os_log_fault_impl ()
#4	0x00000001d33fed44 in SecTrustEvaluateIfNecessary ()
#5	0x00000001d3334250 in SecTrustCopyCertificateChain ()
#6	0x00000001dd43815c in WebCore::CertificateInfo::containsNonRootSHA1SignedCertificate() const ()
#7	0x00000001de3eb3c4 in WebKit::WebPageProxy::didCommitLoadForFrame(WTF::ObjectIdentifier<WebCore::FrameIdentifierType>, WebKit::FrameInfoData&&, WebCore::ResourceRequest&&, unsigned long long, WTF::String const&, bool, WebCore::FrameLoadType, WebCore::CertificateInfo const&, bool, bool, std::__1::optional<WebCore::HasInsecureContent>, WebCore::MouseEventPolicy, WebKit::UserData const&) ()
#8	0x00000001de7a4e6c in WebKit::WebPageProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) ()
#9	0x00000001de1d2ef8 in IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&) ()
#10	0x00000001de41bc6c in WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) ()
#11	0x00000001de1cb62c in IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >) ()
#12	0x00000001de1cadb8 in IPC::Connection::dispatchIncomingMessages() ()
#13	0x00000001deaf5b58 in WTF::RunLoop::performWork() ()
#14	0x00000001deaf6890 in WTF::RunLoop::performWork(void*) ()
#15	0x00000001cb631f54 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#16	0x00000001cb63e32c in __CFRunLoopDoSource0 ()
#17	0x00000001cb5c2210 in __CFRunLoopDoSources0 ()
#18	0x00000001cb5d7ba8 in __CFRunLoopRun ()
#19	0x00000001cb5dced4 in CFRunLoopRunSpecific ()
#20	0x0000000204831368 in GSEventRunModal ()
#21	0x00000001cdabe840 in -[UIApplication _run] ()
#22	0x00000001cdabe4a4 in UIApplicationMain ()
#23	0x00000001023b2a90 in main at /Users/lewissmith/code/paddle-logger-iphone-app/paddle/iPhone App/AppDelegate.swift:32
#24	0x00000001e9b83960 in start ()
```

See also: https://developer.apple.com/forums/thread/712074?page=3

I think this has been an issue for a while, but only recently I have set up stashes to add/remove Superwall as a  result of https://github.com/superwall-me/paywall-ios/issues/67 I am confident that something in Superwall triggers this issue.

**Comment by yusuftor** [comment] 2022-09-29 11:32
Hey, this is an Apple bug in Xcode 14 for the loading of `UIWebViews`. Specifically, calling `webView.load(request)` causes this. We preload paywalls by default which is why you're seeing the error. There isn't actually a way to stop this from appearing, because Apple don't allow us to run that on a background thread. I've already filed a bug report with Apple but haven't heard anything back.
You can turn off preloading of web views if you'd like with the following code:

```
let options = PaywallOptions()
options.shouldPreloadPaywalls = false

Paywall.configure(
  apiKey: apiKey,
  delegate: shared,
  options: options
)
```

**Comment by lewis-smith** [comment] 2022-09-29 14:40
Thank you for the update. Do you mind sharing the FB number so I can add it
to the post I linked?

**Comment by yusuftor** [comment] 2022-09-29 15:00
Sure: FB11618231

**Comment by michaeljajou** [comment] 2022-10-14 16:10
I am having this issue sometimes and it points to  

`SWPaywallViewController`
`
var isActive: Bool {
    return isPresented || isBeingPresented
}
`

is being used, is this in the same case? Can this be a breaking issue at all?

**Comment by yusuftor** [comment] 2022-10-14 16:27
@michaeljajou what you've described is a different issue. This thread is actually about an Xcode bug, whereas yours looks like you might be calling Superwall's config from a background thread. Please could you open another issue and detail what you do to get that warning? Thanks!

**Comment by yusuftor** [comment] 2022-10-14 18:28
@michaeljajou it could also be tracking an event in the background. Btw we’re making sure this sort of thing won’t be able to happen in v3.0 of the SDK.

**Comment by michaeljajou** [comment] 2022-10-14 19:09
Gotcha, then that is definitely it. It happened when I was logging a user out, which then resets the paywall users which doesn't not occur on the main thread. 

For now I will run all paywall methods on the main thread.

Any idea when V3 will be released?

**Comment by yusuftor** [comment] 2022-10-14 19:12
@michaeljajou Thanks for the clarification, I'll do a bugfix release for this next week! V3 doesn't have an ETA yet but will be a little while.

**Comment by michaeljajou** [comment] 2022-10-14 20:46
No problem, so I've essentially narrowed the above issue down to calling `Paywall.reset()` which is required to be called on the Main Thread, but this also blocks the main thread causing dropped frames

**Comment by yusuftor** [comment] 2022-10-17 10:33
@michaeljajou I couldn't reproduce the stalling between calling identify on bg and reset on the main thread. The way this works in v3 will be different anyway, but I have got a fix for your Main Thread warning, meaning you'll be able to call reset on the bg thread in the next release.

**Comment by yusuftor** [comment] 2023-01-10 16:24
Just closing this issue now. We just have to wait for Apple to release an update to Xcode that fixes the main thread warning bug. Fortunately it doesn't affect anything in our SDK.

**Closed by yusuftor** 2023-01-10 16:24 UTC
